---
title: "Lesson 04"
author: "Matheus Ardigueri"
date: "2026-08-27"
output: html_document
---

```{r}
# install.packages("grid.Extra")
# install.packages("ggpubr")
library(lme4)
library(dplyr)
library(tidyverse)
library(janitor)
```

```{r Creating a matrix}
mat <- matrix(1:4693, ncol = 19) # matrix function to create matrix 1:4693 will create values inside this interval

nrow(mat)
```

```{r Accessing data inside a matrix}
mat[47, 2:7] # What is in row 47, columns 2 7 by 7
```

```{r}
A <- matrix(c(51, -3.5, 0, 21, 7.3, -2.1),
            ncol = 2)

t(A)

t(A) * 1:3

```
```{r Creating a list with multiple element assigned}
time <- c(1, 4, 6, 12)

pass <- c(TRUE, FALSE, FALSE)

name <- c("Jon", "Maria", "Maria", "Amy", "Tai", "Tai")

# Put the vectors into a single list
my_list <- list(
  time =time,
  pass = pass,
  name = name
)

my_list
```

```{r Subset time element with brackets}
my_list["time"] # Single braquet will access only TIME column in smaller list
 
my_list[["time"]] # Double braquets will access values.
```

```{r Subset 2-4 of name with $}
my_list$name[2:4]
```

my_list["time"]     # returns a list
my_list[["time"]]   # returns the vector
my_list$time        # also returns the vector

```{r Scan function}
scan("../data/04_scan_demo.txt", what = "numeric")

# setwd() - Sets the working directory
# getwd()  - gets the working directory
```
```{r Read Table function to read excel style but txt files space and tab}
mydata = read.table("../data/04_read_table_demo.txt", header = T)

mydata

read.delim() # Tab-delimited 
read.csv() # comma-separated
```
```{r Writing data out}

write.table(mydata, file = "../data/04_table_out.txt")

write.csv(mydata, file = "../data/04_table_out.csv")
```

```{r}
var <- read.csv("../data/04_input1.csv")

var

```
```{r}
var$collector <- NULL

write.csv(var, file = "../output/04_outputexercise.csv")
```


== Equal to
!= Not equal to
> Greater then
< Smaller then
NA = Missing
NaN Not a Number
is.na(), is.nan()
is.finite()


```{r}
5 > 4 

5 == 1:10

NA 
```

Boolean logic is the mathematics of working with things that are either true or false. Boolean are very usefull for combinations of conditionals, using AND, OR or NOT.
AND - is TRUE only. & - Vector, && Single
OR - One of them needs to be TRUE.
NOT - is FALSE only.

```{r}

T && F
T & c(F, T, T)

my_index <- (1:10 < 8) & (21:30 == 25)

(1:10)[my_index]


```

